# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-Socket-SecureSocks
version:      0.02
version_from: SecureSocks.pm
installdirs:  site
requires:
    IO::Socket::Socks:             
    IO::Socket::SSL:               

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
